In [ ]:
import requests



url = "https://api.coinpaprika.com/v1/tickers/{coin_id}?quotes=USD"

coins_id= {'btc-bitcoin','eth-ethereum','trx-tron'}

coin_data = []


##url.format here is used to treat placeholders in url
for coin in coins_id:
    response = requests.get(url.format(coin_id = coin))
    response.raise_for_status()
    coin_data.append(response.json())

In [100]:
##The first step in transformation is picking the useful data

## The pd.json_normalized command is very useful especially in instances where you have dictionaries inside other dictionaries


##Looking at the normalized columns you can tell that the data has been flattened out into header and data instead of sub dictionaries


##this way, one can have same output for multiple coins withour feeling overwhelmed by the screen output

In [89]:
## Next step is to normalize data for the three coins that we have
import pandas as pd

coins_df = pd.json_normalize(coin_data)
coins_df.head()

,id,name,symbol,rank,total_supply,max_supply,beta_value,first_data_at,last_updated,quotes.USD.price,...,quotes.USD.percent_change_1h,quotes.USD.percent_change_6h,quotes.USD.percent_change_12h,quotes.USD.percent_change_24h,quotes.USD.percent_change_7d,quotes.USD.percent_change_30d,quotes.USD.percent_change_1y,quotes.USD.ath_price,quotes.USD.ath_date,quotes.USD.percent_from_price_ath
0,btc-bitcoin,Bitcoin,BTC,1,20065738,21000000,0.991992,2010-07-17T00:00:00Z,2026-08-04T16:12:15Z,64003.989680,...,0.05,0.91,0.42,0.39,0.40,0,0,126173.177785,2025-10-06T19:00:40Z,-49.30
1,trx-tron,TRON,TRX,8,94891469516,0,0.303012,2017-09-13T00:00:00Z,2026-08-04T16:08:13Z,0.328562,...,-0.26,-0.21,-0.05,-0.20,1.40,0,0,0.440441,2024-12-04T00:12:23Z,-25.45
2,eth-ethereum,Ethereum,ETH,2,120232214,0,1.436710,2015-08-07T00:00:00Z,2026-08-04T16:08:13Z,1869.830301,...,0.09,0.68,0.29,0.18,-2.56,0,0,4946.229670,2025-08-24T19:24:38Z,-62.19

In [91]:
## The next step is dropping the columns you dont require

coins_df.drop(columns=['first_data_at','quotes.USD.percent_change_1h', 'quotes.USD.percent_change_30m', 'quotes.USD.percent_change_6h', 
                       'quotes.USD.percent_change_12h'], inplace= True)

In [92]:
## Drop a few other columns
coins_df.columns

Index(['id', 'name', 'symbol', 'rank', 'total_supply', 'max_supply',
       'beta_value', 'last_updated', 'quotes.USD.price',
       'quotes.USD.volume_24h', 'quotes.USD.volume_24h_change_24h',
       'quotes.USD.market_cap', 'quotes.USD.market_cap_change_24h',
       'quotes.USD.percent_change_15m', 'quotes.USD.percent_change_24h',
       'quotes.USD.percent_change_7d', 'quotes.USD.percent_change_30d',
       'quotes.USD.percent_change_1y', 'quotes.USD.ath_price',
       'quotes.USD.ath_date', 'quotes.USD.percent_from_price_ath'],
      dtype='str')

In [97]:
coins_df.drop(columns=['quotes.USD.percent_change_7d',
                       'quotes.USD.percent_change_1y',
                       'quotes.USD.percent_change_24h',
                       'quotes.USD.percent_change_30d',
                       'quotes.USD.percent_change_15m'], inplace = True)

In [101]:
coins_df.head()

,id,name,symbol,rank,total_supply,max_supply,beta_value,last_updated,quotes.USD.price,quotes.USD.volume_24h,quotes.USD.volume_24h_change_24h,quotes.USD.market_cap,quotes.USD.market_cap_change_24h,quotes.USD.ath_price,quotes.USD.ath_date,quotes.USD.percent_from_price_ath
0,btc-bitcoin,Bitcoin,BTC,1,20065738,21000000,0.991992,2026-08-04T16:12:15Z,64003.989680,1.919765e+10,-5.27,1284287479894,0.39,126173.177785,2025-10-06T19:00:40Z,-49.30
1,trx-tron,TRON,TRX,8,94891469516,0,0.303012,2026-08-04T16:08:13Z,0.328562,3.445517e+08,-3.23,31177740001,-0.20,0.440441,2024-12-04T00:12:23Z,-25.45
2,eth-ethereum,Ethereum,ETH,2,120232214,0,1.436710,2026-08-04T16:08:13Z,1869.830301,5.514162e+09,-5.15,225176774704,0.18,4946.229670,2025-08-24T19:24:38Z,-62.19

In [102]:
coins_df.columns

Index(['id', 'name', 'symbol', 'rank', 'total_supply', 'max_supply',
       'beta_value', 'last_updated', 'quotes.USD.price',
       'quotes.USD.volume_24h', 'quotes.USD.volume_24h_change_24h',
       'quotes.USD.market_cap', 'quotes.USD.market_cap_change_24h',
       'quotes.USD.ath_price', 'quotes.USD.ath_date',
       'quotes.USD.percent_from_price_ath'],
      dtype='str')

In [105]:
coins_df.rename(columns={'quotes.USD.price':'price_USD', 
                         'quotes.USD.volume_24h':'volume_in_24h',
                         'quotes.USD.volume_24h_change_24h':'volume_change_in_24h',
                         'quotes.USD.market_cap':'mkt_cap',
                         'quotes.USD.market_cap_change_24h':'mkt_cap_change',
                         'quotes.USD.ath_price':'ath_price', 
                         'quotes.USD.ath_date':'ath_date',
                         'quotes.USD.percent_from_price_ath':'%_from_price_ath'
                        }, inplace=True
                )

In [106]:
coins_df.head()

,id,name,symbol,rank,total_supply,max_supply,beta_value,last_updated,price_USD,volume_in_24h,volume_change_in_24h,mkt_cap,mkt_cap_change,ath_price,ath_date,%_from_price_ath
0,btc-bitcoin,Bitcoin,BTC,1,20065738,21000000,0.991992,2026-08-04T16:12:15Z,64003.989680,1.919765e+10,-5.27,1284287479894,0.39,126173.177785,2025-10-06T19:00:40Z,-49.30
1,trx-tron,TRON,TRX,8,94891469516,0,0.303012,2026-08-04T16:08:13Z,0.328562,3.445517e+08,-3.23,31177740001,-0.20,0.440441,2024-12-04T00:12:23Z,-25.45
2,eth-ethereum,Ethereum,ETH,2,120232214,0,1.436710,2026-08-04T16:08:13Z,1869.830301,5.514162e+09,-5.15,225176774704,0.18,4946.229670,2025-08-24T19:24:38Z,-62.19

In [115]:
## Changing a string to a timestamp

coins_df['last_updated'] = pd.to_datetime(coins_df['last_updated'])

In [113]:
## the final process in transformation is getting a timestamp from last updated
import datetime

coins_df['time_last_updated'] = coins_df['last_updated'].dt.time

In [114]:
coins_df.head()

,id,name,symbol,rank,total_supply,max_supply,beta_value,last_updated,price_USD,volume_in_24h,volume_change_in_24h,mkt_cap,mkt_cap_change,ath_price,ath_date,%_from_price_ath,time_last_updated
0,btc-bitcoin,Bitcoin,BTC,1,20065738,21000000,0.991992,2026-08-04 16:12:15+00:00,64003.989680,1.919765e+10,-5.27,1284287479894,0.39,126173.177785,2025-10-06T19:00:40Z,-49.30,16:12:15
1,trx-tron,TRON,TRX,8,94891469516,0,0.303012,2026-08-04 16:08:13+00:00,0.328562,3.445517e+08,-3.23,31177740001,-0.20,0.440441,2024-12-04T00:12:23Z,-25.45,16:08:13
2,eth-ethereum,Ethereum,ETH,2,120232214,0,1.436710,2026-08-04 16:08:13+00:00,1869.830301,5.514162e+09,-5.15,225176774704,0.18,4946.229670,2025-08-24T19:24:38Z,-62.19,16:08:13

In [117]:
## The next step is the loading where we get to load the extracted data from the website

import os
from dotenv import load_dotenv

##This command enables us to read from .env file
load_dotenv()

DATABASE_NAME = os.getenv('DATABASE_NAME')
DATABASE_USER = os.getenv('DATABASE_USER')
DATABASE_HOST = os.getenv('DATABASE_HOST')
DATABASE_PASSWORD =os.getenv('DATABASE_PASSWORD')
DATABASE_PORT= os.getenv('DATABASE_PORT')

In [ ]:
## When you want to pip install psycopg2 you ussually install psycopg2-binary